### ISSUE TITLE
[BUG] YOU GOT CAUGHT BY CHINESE POLICE

### ISSUE THREAD

**Issue by Kkaiyuanwg** [otema666/discord-token-login#1]
YOU GOT CAUGHT BY CHINESE POLICE!
![image](https://user-images.githubusercontent.com/118371002/235320952-032ec86e-1f9f-4553-9ede-cad44d761a5e.png)

**Comment by Kkaiyuanwg** [comment]
Va un poco mal eh

**Comment by otema666** [comment]
Hola chinaco, el programa puede que falle en las ultimas versiones, pero por el resto, funciona sin problema. Si encuentras algun otro bug no dudes en notificarlo.
